---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

transport:
      name: winrm
      elevated: true
      
platforms:
  - name: ubuntu-14.04
  - name: centos-7.2
  - name: windows-2012r2
    driver_config:
      box: opentable/win-2012r2-standard-amd64-nocm
    
      
suites:
  - name: default
    run_list:
      - recipe[gnugpg::default]
    attributes:
